name: Testnet Deployment

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.15.0 ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Write config
      uses: schdck/create-env-json@v1
      with:
        file-name: 'src/config/config.json'
        CLIENT_PASSPHRASE: ${{ secrets.LEIF_TESTNET_CLIENT_PASSPHRASE }}
        CLIENT_PRIVATE_KEY: ${{ secrets.LEIF_TESTNET_CLIENT_PRIVATE_KEY }}
        LEIF_APP_PUBLIC_KEY: ${{ secrets.LEIF_TESTNET_APP_PUBLIC_KEY }}
        LEIF_APP_AAT_SIGNATURE: ${{ secrets.LEIF_TESTNET_APP_AAT_SIGNATURE }}
        DISPATCHERS: "https://node1.testnet.pokt.network,https://node2.testnet.pokt.network,https://node3.testnet.pokt.network,https://node4.testnet.pokt.network,https://node5.testnet.pokt.network"
        WALLET_BASE_URL: "https://wallet.testnet.pokt.network"
        DASHBOARD_BASE_URL: "https://dashboard.testnet.pokt.network"
        CHAIN: "0002"
        CHAIN_ID: "testnet"
        ADDRESS: "0594a790e92d423e565652ae16678f3329ec9985"
        BLOCK_TIME: "900000"
        HTTP_PROVIDER: "https://node1.testnet.pokt.network:443"
        PROVIDER_TYPE: "http"
        AAT_VERSION: "0.0.1"
        MAX_DISPATCHERS: "5"
    - name: NPM install
      run: npm install
    - name: Production build
      run: npm run build
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_TESTNET_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "build"
    - name: Clear CloudFront Cache
      uses: awact/cloudfront-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        DISTRIBUTION_ID: ${{ secrets.AWS_TESTNET_DISTRIBUTION_ID }}
    
