name: Testnet Deployment

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.15.0 ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM install
      run: npm install
    - name: create production env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_CLIENT_PASSPHRASE: ${{ secrets.LEIF_TESTNET_CLIENT_PASSPHRASE }}
        envkey_CLIENT_PRIVATE_KEY: ${{ secrets.LEIF_TESTNET_CLIENT_PRIVATE_KEY }}
        envkey_LEIF_APP_PUBLIC_KEY: ${{ secrets.LEIF_TESTNET_APP_PUBLIC_KEY }}
        envkey_LEIF_APP_AAT_SIGNATURE: ${{ secrets.LEIF_TESTNET_APP_AAT_SIGNATURE }}
        envkey_WALLET_BASE_URL: "https://wallet.testnet.pokt.network"
        envkey_DASHBOARD_BASE_URL: "https://dashboard.testnet.pokt.network"
        envkey_GATEWAY_BASE_URL: "https://gateway.pokt.network/v1/lb/60a2ac11b1747c6552385c61"
        envkey_CHAIN: "0002"
        envkey_CHAIN_ID: "testnet"
        envkey_ADDRESS: "0594a790e92d423e565652ae16678f3329ec9985"
        envkey_HTTP_CONFIG: '{ "timeout": 0, "headers": { "Content-Type": "application/json" } }'
        file_name: .env.production
    - name: Production build
      run: npm run build
      env:
        CLIENT_PASSPHRASE: ${{ secrets.LEIF_TESTNET_CLIENT_PASSPHRASE }}
        CLIENT_PRIVATE_KEY: ${{ secrets.LEIF_TESTNET_CLIENT_PRIVATE_KEY }}
        LEIF_APP_PUBLIC_KEY: ${{ secrets.LEIF_TESTNET_APP_PUBLIC_KEY }}
        LEIF_APP_AAT_SIGNATURE: ${{ secrets.LEIF_TESTNET_APP_AAT_SIGNATURE }}
        WALLET_BASE_URL: "https://wallet.testnet.pokt.network"
        DASHBOARD_BASE_URL: "https://dashboard.testnet.pokt.network"
        GATEWAY_BASE_URL: "https://gateway.pokt.network/v1/lb/60a2ac11b1747c6552385c61"
        CHAIN: "0002"
        CHAIN_ID: "testnet"
        ADDRESS: "0594a790e92d423e565652ae16678f3329ec9985"
        HTTP_CONFIG: '{ "timeout": 0, "headers": { "Content-Type": "application/json" } }'
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_TESTNET_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "build"
    - name: Clear CloudFront Cache
      uses: awact/cloudfront-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        DISTRIBUTION_ID: ${{ secrets.AWS_TESTNET_DISTRIBUTION_ID }}

